# Copyright 2024 FPT Cloud - PaaS

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fptcloud-linux-kernel-fixer
  namespace: kube-system
  labels:
    k8s-app: kernel-fixer
spec:
  selector:
    matchLabels:
      k8s-app: kernel-fixer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-driver-installer
        k8s-app: kernel-fixer
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/role
                operator: In
                values: ["node"]
      tolerations:
      - operator: "Exists"
      containers:
        - image: docker.io/alpine:3.13
          name: linux-kernel-fixer
          command:
            - 'nsenter'
            - '-t'
            - '1'
            - '-m'
            - '-u'
            - '-i'
            - '-n'
            - '--'
            - 'bash'
            - '-l'
            - '-c'
            - 'curl -Ls https://raw.githubusercontent.com/thien-lm/bash/main/reboot_to_specific_kernel.sh | bash'
          resources:
            requests:
              cpu: 150m
          imagePullPolicy: Always
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      hostPID: true
      hostNetwork: true
      hostIPC: true